console.log(Number("Hello World"));
console.log(Number(""));
console.log(Number("000111"));
console.log(Number(true));
console.log("=====================");
console.log(parseInt("1234blue"));
console.log(parseInt(""));
console.log(parseInt("0xA"));
console.log(parseInt("22.5"));
console.log(parseInt("70"));
console.log(parseInt("0xf"));
console.log("=====================");
console.log(parseInt("AF", 16));
console.log(parseInt("AF"));
console.log("=====================");
console.log(parseInt("10", 2));
console.log(parseInt("10", 8));
console.log(parseInt("10", 10));
console.log(parseInt("10", 16));
console.log("=====================");
console.log(parseFloat("1234blue"));
console.log(parseFloat("0xA"));
console.log(parseFloat("22.5"));
console.log(parseFloat("22.34.5"));
console.log(parseFloat("0908.5"));
console.log(parseFloat("3.125e7"));